[package]
name = "enforcer"
version = "0.2.1"
authors = ["Oliver Mueller <oliver.mueller@gmail.com>"]

[dependencies]
glob = "*"
docopt = "0.6"
rustc-serialize = "0.3"
log = "0.3"
env_logger = "0.3"
toml = "0.1"
